se arreglan tíldes del contenido
robertodiazch/hyperblog pull request #1
Opened 2020-09-29 23:35 UTC by robertodiazch

Esta es una prueba de un pull request corrigiendo las tildes del contenido

2020-09-29 23:42 UTC, paramigranja requested changes
En vez de usar tildes directas, mejor usar html

2020-09-29 23:55 UTC, paramigranja requested changes
Hola Roberto, mejor usar html en vez de tildes

2020-09-30 00:04 UTC, robertodiazch commented
Se han realizado los cambios, porfa realizar el merge

2020-09-30 00:07 UTC, paramigranja approved these changes
Listos!!!

2020-09-30 00:08 UTC, merged